### ISSUE TITLE
Missing hotkey for save button

### ISSUE THREAD

**Issue by bjarnef** [Novicell/novicell-mapbuilder#1]
The save button is missing the hotkey action `hotkey="ctrl+s"`, so you can hit `ctrl+s` to save - just like when content, media, document types etc.

There is also a `hotkey-when-hidden` directive - if true it allow to use the hot-key action, even the button is hidden with css.

**Comment by marklonquist** [comment]
Thank you @bjarnef - This will be added in 1.0.2

**Comment by marklonquist** [comment]
fixed by 2cd2c49
