### ISSUE TITLE
Map not rendering with coordinates

### ISSUE THREAD

**Issue by tappiorg** [Novicell/novicell-mapbuilder#11]
First off thank you for your efforts on this. I set up a map, the datasource (mapped to a doc type and the requisite fields), and the coordinates are not rendering on the resulting map. It centers on Denmark every time (the location is in New Mexico, USA). 

Here is the JS that is generated. Even if I explicitly add the parameters in the RenderMap function, nothing changes - the map is still centered over Denmark.

```
<script type="text/javascript">
        ncmapbuilder.generator.init('map', '[2125,2135]', 'name', 'longitude');
    </script>
```

Any assistance would be great.

**Comment by marklonquist** [comment]
Hi tappiorg

Thank you for the kind words :-)

I seem to have forgotten the fields to set the center of the map. I will get that added today. And will upload a new package.

I will comment on your issue again, once this is done.

**Comment by marklonquist** [comment]
If you want a quick workaround, you can go to:
App_Plugins/NcMapBuilder/FrontendJS/generator.js

and change line 79:
var centerCoordinates = new google.maps.LatLng(mapsModel.Center[0], mapsModel.Center[1]);

to:
var centerCoordinates = new google.maps.LatLng(34.1503759,-108.2692442);

You might have to tweak the coordinates.

There is a new build coming up shortly though, which have an option for centering around the markers.

**Comment by tappiorg** [comment]
Awesome - thanks a lot! That did work. I will wait for the new build, though, as I am not in a huge rush.

**Comment by marklonquist** [comment]
Hi!

It took a while longer than expected.. Been busy at work. But there is now a version 1.0.2 available.

You can either download it on Our or go to releases here on github:
https://github.com/Novicell/novicell-mapbuilder/releases/tag/1.0.2

Again, thank you for letting us know about this. 😄
