### ISSUE TITLE
Has anyone got this working on v7.5

### ISSUE THREAD

**Issue by trevorloader** [Novicell/novicell-mapbuilder#12]
Hi,

I've installed the package, recycled app pools etc etc and cannot get the new tree item (map builder) to appear on the left hand side...so cannot configure the datasource etc.

Is anyone else using v7.5.3 and has got this package to work?

TIA
Trevor

**Comment by adampnielsen** [comment]
Hi Trevor.

Have a look in your user section. 
I think you simply need to grant your user permissions to the MapBuilder section. 

Let me know if that works for you. :)

Adam

**Comment by trevorloader** [comment]
Bugger, yep that worked. Duh!

**Comment by hesselberg** [comment]
Closing the issue as it seems to have been fixed :-)
