### ISSUE TITLE
Scope error with "apiPath"

### ISSUE THREAD

**Issue by soreng** [Novicell/novicell-mapbuilder#14]
https://github.com/Novicell/novicell-mapbuilder/blob/d3c122a8b24a43a1d1c1e1af97af0b6d21659718/MapBuilder.Website/App_Plugins/NcMapBuilder/BackOffice/Resources/MapBuilder.Resource.js#L1

the variable (not const) defined in line 1 can be overwritten (and it was in our project), wich caused the mapbuilder to give the dreaded "red bar"-error (404) in umbraco back-office.

**Comment by marklonquist** [comment]
Please make a pull request

**Comment by zimpy** [comment]
https://github.com/Novicell/novicell-mapbuilder/pull/16

**Comment by marklonquist** [comment]
Perfect
