### ISSUE TITLE
Using MapBuilder with TerraType?

### ISSUE THREAD

**Issue by greystate** [Novicell/novicell-mapbuilder#19]
Hi - I'm trying to use MapBuilder for displaying a map.

The Document Type uses the rather awesome TerraType package to set the coordinates - it stores a JSON chunk like this:

```json
{
  "zoom": 11,
  "position": {
    "id": "WGS84",
    "datum": "56.485918,9.727836"
  }
}
```

So, two questions:

- Does MapBuilder require the coordinates property to be stored as plain text (i.e., `lat,lng`)?
- (If it does) Is there a way to hook into getting the value from the property to "fix" this? (So I don't have to use a simpler Maps Property and thus require my editors to re-pick 80+ locations...)

**Comment by greystate** [comment]
Ok - can see that I might be able to tweak the `/App_Plugins/NcMapBuilder/FrontendJS/generator.js` file and handle this...

(Will report back :-)

**Comment by greystate** [comment]
Hmm - nope... need to modify the `GetMapModel` API method [here](https://github.com/Novicell/novicell-mapbuilder/blob/d3c122a8b24a43a1d1c1e1af97af0b6d21659718/MapBuilder.Library/Helpers/MapModelHelper.cs#L30)

**Comment by marklonquist** [comment]
You could hook into the Umbraco published event and copy the "datum" into a umbraco label, and then get the coordinates from that label in MapBuilder.

But what you want is not something MapBuilder can do out of the box 😞 

You are, however, free to download the source and alter it in any way you want. 😃

**Comment by greystate** [comment]
Thanks Mark - that's actually not a bad idea, using an event... 🤔 💭 

#epiphany

🚀 👍 🥇
