### ISSUE TITLE
Coordinates not being parsed correctly

### ISSUE THREAD

**Issue by greystate** [Novicell/novicell-mapbuilder#20]
I was trying to use MapBuilder to display a map but I didn't get any output. No errors in console, no nothing.

Upon inspection I could see that the coordinates returned from the API call were way off, e.g. instead of getting `Coordinates: [56.34670, 3.34675]`,  I'd be getting `Coordinates: [5634670, 334675]` so GMaps deemed nothing to show, I guess :-)

What I've deducted from this is that the `double.Parse` function being [used here](https://github.com/Novicell/novicell-mapbuilder/blob/d3c122a8b24a43a1d1c1e1af97af0b6d21659718/MapBuilder.Library/Helpers/MapModelHelper.cs#L92) interprets the dot in "56.34670" as a thousands separator and throws it away...

I don't know that much about how to "correctly" account for different cultures in C# (or how an Umbraco node's culture affects the code running) etc., but I was able to fix the problem in my site (runs as Danish but I tried English and American too with no luck) by replacing the call with this:

`[...]  .Select(d => double.Parse(d, CultureInfo.InvariantCulture)) [...]`

Has that not been an issue for anyone else?

**Comment by marklonquist** [comment]
Hi Greystate

It makes sense. Can you make a pull request with the change?
