### ISSUE TITLE
Bottom cover part of scrollbar

### ISSUE THREAD

**Issue by bjarnef** [Novicell/novicell-mapbuilder#3]
It seems the bottom with save button cover a part of the scrollbar, which it doesn't in core.

![image](https://cloud.githubusercontent.com/assets/2919859/17410170/da80d9ac-5a72-11e6-84d7-2faa124f586d.png)

**Comment by marklonquist** [comment]
Thank you @bjarnef - This will be fixed in 1.0.2

**Comment by marklonquist** [comment]
Will be fixed doing refactoring of edit page using in case #8
