### ISSUE TITLE
Some adjustments for project

### ISSUE THREAD

**Issue by bjarnef** [Novicell/novicell-mapbuilder#4]
Can we include an embed SQL CE database in `/App_Data` folder in this project, like we do in Analytics project over here and note login in readme? https://github.com/warrenbuckley/Analytics/tree/develop/Analytics.Site/App_Data

Furthermore I think there is no reason to include `/App_Browsers` and `/Config/splashes` folder in library: https://github.com/Novicell/novicell-mapbuilder/tree/master/MapBuilder.Library

In an single line you are using you own localize directive https://github.com/Novicell/novicell-mapbuilder/blob/4a3c0ecfaeaa2a540ddb1f78e7dba6627a911feb/MapBuilder.Website/App_Plugins/NcMapBuilder/BackOffice/MapBuilderTree/edit.html#L20 ... is there a reason why not just use `<localize>` element directive?

If you want to limit support for this project to Umbraco 7.4+ it would probably be easier to maintain and you can use all the new cool directives/compents, e.g. you can consider to use `umb-table` for this part: https://github.com/Novicell/novicell-mapbuilder/blob/4a3c0ecfaeaa2a540ddb1f78e7dba6627a911feb/MapBuilder.Website/App_Plugins/NcMapBuilder/BackOffice/MapBuilderTree/edit.html#L22-L53

Most of the stuff is documented here https://our.umbraco.org/apidocs/ui/#/api .. but some might be missing, so it might be better to stuff source code although there might be some changes for v7.5.0

E.g. something like this https://github.com/umbraco/Umbraco-CMS/blob/75c2b07ad3a093b5b65b6ebd45697687c062f62a/src/Umbraco.Web.UI.Client/src/views/media/edit.html to build to view with tabs, header, footer with buttons.

**Comment by marklonquist** [comment]
This is more than one issue, please submit multiple issues rather than collecting them in one.
Also, you can fork the project, and make pull requests. :-)

**Comment by bjarnef** [comment]
Done :) closing this.
