### ISSUE TITLE
Include an embed SQL CE database

### ISSUE THREAD

**Issue by bjarnef** [Novicell/novicell-mapbuilder#5]
Can we include an embed SQL CE database in /App_Data folder in this project, like we do in Analytics project over here and note login in readme? https://github.com/warrenbuckley/Analytics/tree/develop/Analytics.Site/App_Data

**Comment by marklonquist** [comment]
This makes sense.. That way for development, we dont need a actual MSSQL db.. This is scheduled for 1.0.2
