### ISSUE TITLE
Remove /App_Browsers and /Config/splashes folder in library

### ISSUE THREAD

**Issue by bjarnef** [Novicell/novicell-mapbuilder#6]
I think there is no reason to include /App_Browsers and /Config/splashes folder in library: https://github.com/Novicell/novicell-mapbuilder/tree/master/MapBuilder.Library

**Comment by marklonquist** [comment]
Agreed

**Comment by soreng** [comment]
the files are still in the project 👎 
should be removed

**Comment by marklonquist** [comment]
Please make a pull request

**Comment by marklonquist** [comment]
They are not in the .Library project, Closing.
