### ISSUE TITLE
Remove custom localize directive

### ISSUE THREAD

**Issue by bjarnef** [Novicell/novicell-mapbuilder#7]
In an single line you are using you own localize directive https://github.com/Novicell/novicell-mapbuilder/blob/4a3c0ecfaeaa2a540ddb1f78e7dba6627a911feb/MapBuilder.Website/App_Plugins/NcMapBuilder/BackOffice/MapBuilderTree/edit.html#L20 ... is there a reason why not just use <localize> element directive?

**Comment by marklonquist** [comment]
This is kind of a bug.. Will be removed in 1.0.2
